debug: true
kafka:
  zookeeper:
    connect: kafka:9092
  topic: dp.enrichment
  message-key: si.key
  auto-start: false
  consumers: 10
spring:
  main:
    web-application-type: servlet
    banner-mode: log
  rabbitmq:

    host: ${RABBITMQ_HOST:rabbitMq}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}

    connection:
      recovery:
        enabled: true
        interval: 1000

  consumer:
    index-queue-name: ${INDEX_QUEUE}

  kafka:
    publisher:
      group-id: documentIndexer
      enable-auto-commit: true
      auto-commit-interval: 100
#      max-poll-interval: 300000
      max-poll-records: 10
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: DocumentIndexer

  jmx:
    enabled: false
  activemq:
    in-memory: false
  artemis:
    embedded:
      enabled: false
  profiles:
    active: rest, rabbitmq
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
      resolve-lazily: true

enrichment-service:
  retry:
     initialInterval : 50
     multiplier: 2
     maxInterval: 1000
     maxAttempts: 5


server:
  port: 8888
